spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/studyroom;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          timeout: 5000
          starttls:
            enable: true
          auth: false
  jwt:
    secret: ${JWT_SECRET}