logging:
  level:
    com.com.growth.community: trace
    org.springframework.security: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web.servlet: trace

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/studyroom;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_API_KEY}
            client-secret: ${KAKAO_SECRET}
            authorization-grant-type: authorization_code            # yml은 특수문자 사용 시 쌍따옴표를 사용해야함.
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"       # {baseUrl}을 사용하면 현재 스프링 도메인으로 치환해준다.
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize  # 인가코드
            token-uri: https://kauth.kakao.com/oauth/token              # 토큰
            user-info-uri: https://kapi.kakao.com/v2/user/me            # 유저 정보
            user-name-attribute: id                                     # 응답 중 유저를 식별할 수 있는 식별자 정보
  jwt:
    secret: ${JWT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          timeout: 5000
          starttls:
            enable: true
          auth: false